modLoader="javafml"
loaderVersion="[47,)"
license="CC0-1.0"

[[mixins]]
config="simplytentsridingfix.mixins.json"

[[mods]]
modId="simplytentsridingfix"
version="${file.jarVersion}"
displayName="SimplyTents Riding Fix"
authors="deliciousbread481"
description='''修复骑乘状态（如魔女扫帚）下无法收纳帐篷的问题'''

[[dependencies.simplytentsridingfix]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.simplytentsridingfix]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"

[[dependencies.simplytentsridingfix]]
modId="simplytents"
mandatory=true
versionRange="[2.0,)"
ordering="AFTER"
side="BOTH"